#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
echo 'Ceci n'"'"'est pas une page' | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \
    \terror_page 404 /404.html; \
    \tlocation  /xyz { \
        \tinternal; \
    \t}' /etc/nginx/sites-available/default
sudo service nginx start
