#!/usr/bin/env bash
# Configure nginx to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Ceci n'"'"'est pas une page' | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \
    \terror_page 404 /404.html; \
    \tlocation  /xyz { \
        \tinternal; \
    \t}' /etc/nginx/sites-available/default
sudo service nginx start
