#!/usr/bin/env bash
# A Bash script that configures a server to run and listen on port 80

sudo apt update
sudo apt -y install nginx
sudo sed -i 's/listen\s*80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default
sudo service nginx start
